### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by glensbo** [dbosak01/libr#75]
Warning in install.packages :
  package ‘sassy’ is not available (for R version 3.6.2 Patched)
mac 10.14.06
Any ideas?

**Comment by dbosak01** [comment]
Hi glensbo: Sorry, I’m in the middle of redoing the documentation for all my packages, and it is a little messed up right now.  The “sassy” reference on the “libr” package documentation is incorrect.  You can use install.packages(“libr”).    David   Sent from Mail for Windows 10 From: glensboSent: Monday, December 21, 2020 3:16 AMTo: dbosak01/librCc: SubscribedSubject: [dbosak01/libr] installation (#75) Warning in install.packages :package ‘sassy’ is not available (for R version 3.6.2 Patched)mac 10.14.06Any ideas?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by glensbo** [comment]
I think I'll wait some days before I check in again - hope you manage to cope with all the demands
Error in install.packages : object 'libr' not found
> install.packages(libr)
Error in install.packages : object 'libr' not found
> install.packages("libr")
Warning in install.packages :
  package ‘libr’ is not available (for R version 3.6.2 Patched)
> install.packages("sassy")
Warning in install.packages :
  package ‘sassy’ is not available (for R version 3.6.2 Patched)
>

**Comment by dbosak01** [comment]
I can get the documentation fixed pretty quickly.  But it is currently not supporting R 3.6.2.  Is that a requirement for you?  I'm supporting 4.0.0+.

**Comment by glensbo** [comment]
Problem solved Thanks - I only checked RStudio - latest version - updating Rbase solved the problem. Sorry for the inconvenience
