### ISSUE TITLE
Readme is for sassy

### ISSUE THREAD

**Issue by jkaupp** [dbosak01/libr#76]
Readme is for the wrong package.

**Comment by dbosak01** [comment]
Hi Jake: Sorry, I’m redoing all the documentation for my packages right now, and it is a little messed up.  You can use install.packages(“libr”). David  Sent from Mail for Windows 10 From: Jake KauppSent: Monday, December 21, 2020 6:50 AMTo: dbosak01/librCc: SubscribedSubject: [dbosak01/libr] Readme is for sassy (#76) Readme is for the wrong package.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dbosak01** [comment]
This is fixed.  Thanks for noticing.
